"""Public API for SSF2 research environments and policy tooling."""

from .data import Episode
from .env import SSF2Env
from .game.catalog import CHARACTERS, RANDOM, STAGES, Character, Stage
from .game.controls import (
    ALL_BITS,
    ATTACK,
    AUTO_DASH,
    BITS,
    C_DOWN,
    C_LEFT,
    C_RIGHT,
    C_UP,
    Controls,
    DASH,
    DOWN,
    DT_DASH,
    GRAB,
    JUMP,
    JUMP2,
    JUMP3,
    LEFT,
    NOOP,
    RIGHT,
    SHIELD,
    SHIELD2,
    SPECIAL,
    START,
    TAP_JUMP,
    TAUNT,
    UP,
    bit_name_map,
    describe_mask,
)
from .game.launcher import (
    LaunchError,
    ensure_game_running,
    game_log_path,
    port_open,
    stop_game,
)
from .game.players import (
    CPU,
    Character,
    Human,
    Player,
    Stage,
    build_match_config,
    describe_matchup,
)
from .policy import ACTION_TABLE, ACTION_NAMES, ACTION_MASKS, action_index
from .policy.bots import Agent, Bot, FollowBot, PolicyBot, ScriptedBot, ZeroBot
from .policy.observation import (
    CHAR_FEATURES,
    OBS_DIM,
    build_obs,
    char_vec,
    obs_feature_names,
    pick_chars,
)
from .policy.reward import reward_delta
from .protocol import BridgeError, SSF2Bridge

__all__ = [
    "SSF2Bridge",
    "BridgeError",
    "SSF2Env",
    "Episode",
    "Controls",
    "BITS",
    "bit_name_map",
    "describe_mask",
    "NOOP",
    "ALL_BITS",
    "TAP_JUMP",
    "SHIELD",
    "SHIELD2",
    "TAUNT",
    "START",
    "GRAB",
    "SPECIAL",
    "ATTACK",
    "JUMP",
    "JUMP2",
    "JUMP3",
    "RIGHT",
    "LEFT",
    "DOWN",
    "UP",
    "DT_DASH",
    "AUTO_DASH",
    "DASH",
    "C_RIGHT",
    "C_LEFT",
    "C_DOWN",
    "C_UP",
    "LaunchError",
    "ensure_game_running",
    "game_log_path",
    "port_open",
    "stop_game",
    "CHARACTERS",
    "STAGES",
    "RANDOM",
    "Character",
    "Stage",
    "CPU",
    "Human",
    "Player",
    "build_match_config",
    "describe_matchup",
    "Agent",
    "Bot",
    "FollowBot",
    "PolicyBot",
    "ScriptedBot",
    "ZeroBot",
    "ACTION_TABLE",
    "ACTION_NAMES",
    "ACTION_MASKS",
    "action_index",
    "CHAR_FEATURES",
    "OBS_DIM",
    "build_obs",
    "char_vec",
    "obs_feature_names",
    "pick_chars",
    "reward_delta",
]
